#!/usr/bin/env sh

[ -z $1 ] && echo "missing version type: major, minor, or patch" && exit 1

# exit if npm version returned nothing on stdout
echo "npm version $1"
npm version $1

tag=$(cat package.json |jd version |sed -e "s/'//g" |sed -e "s/^/v/")
echo "version: $tag"

echo "updating bower..."
npm run update-bower
git add bower.json

echo "updating build & dist..."
npm run dist
git add dist/wikidata-sdk.js dist/wikidata-sdk.min.js

echo "amending version commit..."
git commit --amend --no-edit
# deleting the tag on npm version commit
# get the version number, remove the quotes, add a v
echo "deleting tag..."
git tag -d $tag
# to re-create it on the completed commit
echo "re-creating tag..."
git tag $tag
echo 'done'
