#!/usr/bin/env bash
git push --tags

wbk_version=$(node -p 'require("./package.json").version')
echo "wbk_version: $wbk_version"

cd ./wikidata-sdk
npm install "wikibase-sdk@${wbk_version}"
npm version "$wbk_version"
git add ./package*.json
git commit -m 'wikidata-sdk: updated'
cd ..

tmp_dir="/tmp/wikidata-sdk-$(date '+%s')"
cp -r ./wikidata-sdk $tmp_dir
cd $tmp_dir
npm publish '.'
