#!/usr/bin/env node
const fs = require('fs')

const { name, version, description, homepage, keywords, license } = require('../package.json')
const bower = require('../bower.json')

bower.name = name
bower.version = version
bower.description = description
bower.homepage = homepage
bower.keywords = keywords
bower.license = license

fs.writeFile('./bower.json', JSON.stringify(bower, null, 2), function (err, res) {
  if (err) {
    console.error(err)
  } else {
    console.log('updated bower.json')
  }
})
