#!/usr/bin/env bash
which doctoc && {
  docs_with_doctoc=$(grep -r 'Summary' docs | sed 's/:.*//')
  doctoc README.md $docs_with_doctoc

  # Override summuries to directly link to the right doc
  sed -i 's/#simplify-claims/simplify_claims.md/' ./docs/simplify_entities_data.md
} || {
  echo "requires to have https://www.npmjs.com/package/doctoc installed, either globally or just in this repo"
  echo "(it is not installed as a dev dependency as the use made of it it's not worth the subdependencies maintainance)"
  exit 1
}
