#!/usr/bin/env bash
set -eu

green_log(){ echo -e "\e[0;32m$1\e[0;0m" ; }

git checkout master

green_log 'update dist...'

green_log 'build...'
npm run build

green_log 'minify...'
npm run minify

green_log 'commit...'
git checkout -B dist
git add dist/wikibase-sdk.js dist/wikibase-sdk.min.js dist/wikidata-sdk.js dist/wikidata-sdk.min.js
git commit -m 'dist: updated'

local last_version="v$(jq '.version' -r < package.json)"
echo "last_version: $last_version"

# Deleting the tag on `npm version` commit
echo "deleting $last_version tag..."
git tag -d $last_version
# to re-create it on the dist commit
echo "re-creating $last_version tag on dist commig..."
git tag $last_version

git push origin -f dist
git push --tags

git checkout master

green_log 'done update dist'
