#!/usr/bin/env bash
set -eu

green_log(){ echo -e "\e[0;32m$1\e[0;0m" ; }

git checkout main

green_log 'ensure lints...'
npm run lint

green_log 'ensure tests...'
npm test

green_log 'update dist...'

green_log 'build...'
npm run build

green_log 'commit...'
git checkout -B dist
git add dist -f
git commit -m 'dist: updated'
